tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    colors: {
                        "on-tertiary-fixed-variant": "#41474f",
                        "on-primary-fixed": "#101f09",
                        "on-secondary": "#223146",
                        "on-surface-variant": "#c3c8c1",
                        "primary-container": "#4b5e41",
                        "on-tertiary-fixed": "#161c23",
                        "inverse-primary": "#516447",
                        "tertiary-container": "#535961",
                        "surface-container-lowest": "#0c0e11",
                        "secondary": "#b8c7e2",
                        "secondary-fixed-dim": "#b8c7e2",
                        "inverse-on-surface": "#2f3034",
                        "surface-variant": "#333538",
                        "outline-variant": "#434843",
                        "on-primary": "#24351c",
                        "on-surface": "#e2e2e6",
                        "primary": "#b8cdaa",
                        "on-primary-fixed-variant": "#3a4c31",
                        "error-container": "#93000a",
                        "on-error": "#690005",
                        "on-background": "#e2e2e6",
                        "tertiary-fixed": "#dde3ec",
                        "tertiary-fixed-dim": "#c1c7d0",
                        "error": "#ffb4ab",
                        "surface-container": "#1e2023",
                        "background": "#111316",
                        "on-tertiary-container": "#cad0d9",
                        "on-secondary-fixed": "#0c1c30",
                        "primary-fixed-dim": "#b8cdaa",
                        "inverse-surface": "#e2e2e6",
                        "outline": "#8d928c",
                        "on-secondary-fixed-variant": "#39485d",
                        "secondary-fixed": "#d4e3fe",
                        "surface-container-low": "#1a1c1f",
                        "on-tertiary": "#2b3138",
                        "on-error-container": "#ffdad6",
                        "tertiary": "#c1c7d0",
                        "surface-bright": "#37393d",
                        "on-secondary-container": "#aab9d3",
                        "surface-dim": "#111316",
                        "secondary-container": "#3b4a60",
                        "primary-fixed": "#d4e9c4",
                        "surface": "#111316",
                        "surface-container-high": "#282a2d",
                        "surface-tint": "#b8cdaa",
                        "on-primary-container": "#c1d6b2",
                        "surface-container-highest": "#333538"
                    },
                    fontFamily: {
                        "headline": ["Space Grotesk"],
                        "body": ["Inter"],
                        "label": ["Inter"]
                    },
                    borderRadius: { "DEFAULT": "0rem", "lg": "0rem", "xl": "0rem", "full": "9999px" },
                },
            },
        }